<%--
  Created by IntelliJ IDEA.
  User: mrz
  Date: 16/7/19
  Time: 下午2:39
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
    <style>
        table{border-collapse:collapse;border-spacing:0;}
        td{
            display:inline-block;
            padding:0px;
            margin:0px;
            border:0px;

        }
        tr{
            display:inline-block;
            padding:0px;
            margin:0px;
            border:0px;
        }
    </style>
</head>
<body>
<table width="640" height="352" style="background: #cccccc;">
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
    <tr>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
        <td>测试数</td>
    </tr>
</table>
</body>
</html>
